name: Generate Snake Game ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake ğŸ
        uses: Platane/snk@master
        with:
          github_user_name: ChoSinHong  # Your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-snake.svg

      - name: Push Snake to GitHub ğŸ—ï¸
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

